language: shell
os: windows

before_install:
  - choco install python
  - python -m pip install --upgrade pip
env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  - pip3 install --upgrade pip
  - pip3 install pytest
  - pip3 install -r ./requirements.txt
script:
  - pytest

