language: shell
os: windows

before_install:
  - scoop install python3.6 -a 32bit
  - python -m pip install --upgrade pip
env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  - pip3 install --upgrade pip
  - pip3 install pytest
  - pip3 install -r ./requirements.txt
  - pip3 install .
script:
  - c:\\programdata\\chocolatey\\lib\\python3-x86_32\\tools\\Scripts\\py.test.exe

