language: shell
os: windows

before_install:
  - choco install curl unzip
  - curl https://www.python.org/ftp/python/3.7.7/python-3.7.7-embed-win32.zip --output py37.zip
  - unzip py37.zip /c/python37
  - unzip /c/python37/python37/python37.zip /c/python37/Scripts
  - python.exe -m pip install --upgrade pip
env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip3 install --upgrade pip
  - pip3 install pytest
  - pip3 install -r ./requirements.txt
  - pip3 install .
script:

