language: shell
os: windows

before_install:
  - choco install curl unzip
  - curl https://www.python.org/ftp/python/3.7.7/python-3.7.7-embed-win32.zip --output ./py37.zip
  - curl https://bootstrap.pypa.io/get-pip.py --output ./get-pip.py
  - dir
  - unzip ./py37.zip -d /c/python37
  - unzip -q /c/Python37/python37.zip -d /c/Python37/Scripts
  - python.exe ./get-pip.py
  - dir /c/Python37/
  - dir /c/Python37/Scripts
#  - /c/Python37/Scripts/pip install --upgrade pip
env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - del /c/Python37/python37._pth
  - /c/Python37/Scripts/pip install --upgrade pip
  - /c/Python37/Scripts/pip install pytest
  - /c/Python37/Scripts/pip install -r ./requirements.txt
  - /c/Python37/Scripts/pip install .

script:
  py.test
